---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: cdi-operator
  name: cdi-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: hyperconverged-cluster-operator
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: kubevirt-operator
  name: kubevirt-operator
  namespace: kubevirt-hyperconverged
